version: 2
updates:
- package-ecosystem: cargo
  directory: "/api"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
  - dependency-name: once_cell
    versions:
    - 1.5.2
    - 1.6.0
    - 1.7.0
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: futures-util
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: tokio
    versions:
    - 0.2.24
