[site]
title = ""
subtitle = ""
description = ""
keywords = []
author = ""
email = ""
utc_offset = 800
theme = "resource"
domain = ""
domain_root = ""
default_template = "page.html"

[extra]

[watch]
exclusive = [
    "templates/resource/statics/style.css",
    "templates/resource/statics/trending"
]

[hook]
before_build = [
    { dir = "pages/rust_trending_page", command = "yarn" },
    { dir = "pages/rust_trending_page", command = "yarn build" },
    "rm -rf templates/resource/statics/trending",
    "mv pages/rust_trending_page/public/build templates/resource/statics/trending",
    { dir = "templates/resource/statics", command = "lessc style.less style.css" }
]