
[config]
default_to_workspace = true
# ---- BUILD & CREATE WASMS ----

#[tasks.client_build]
#description = "Client Build"
#workspace = true
#command = "cargo"
#args = ["make", "--makefile","client/Makefile.toml", "build"]

[tasks.build]
description = "Build"
workspace = true
command = "cargo"
args = ["build"]

[tasks.server_run]
description = "Build"
workspace = false
command = "cargo"
args = ["run"]

[tasks.release]
description = "Build, with the --release flag"
workspace = true
command = "cargo"
args = ["build", "--release"]