name: Master deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update Rust Stable
        run: rustup update stable
      - name: Run tests
        run: cargo test --verbose
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update Rust Stable
        run: rustup update stable
      - name: Docker build
        run: docker build --tag ${{ secrets.DOCKER_REPO }}:$GITHUB_SHA .
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push image
        run: docker push ${{ secrets.DOCKER_REPO }}:$GITHUB_SHA
      - name: deploy to service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            /root/update_resource.sh $GITHUB_SHA