name: Master deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update Rust Stable
        run: rustup update stable
      - name: Run tests
        run: cargo test --verbose
      - name: Docker build
        run: docker build --tag $DOCKER_REPO:$GITHUB_SHA .
      - name: docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: docker push image
        run: docker push $DOCKER_REPO:$GITHUB_SHA